// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const background: string;
export const section: string;
export const avatar: string;
export const item: string;
export const name: string;
export const contactInformation: string;
