// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const experienceListItems: string;
export const subtitle: string;
export const description: string;
