// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const skillBarContent: string;
export const skillContainer: string;
export const skillsContainer: string;
export const skillsContainerItems: string;
