// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const contactItem: string;
export const contactItemIcon: string;
export const contactItemRow: string;
